// Generated by CoffeeScript 1.11.1
(function() {
  var querystring, start, upload;

  querystring = require("querystring");

  start = function(response) {
    var body, sleep;
    console.log("Request handler 'start' was called.");
    sleep = function(milliSeconds) {
      var results, startTime;
      startTime = new Date().getTime();
      results = [];
      while (new Date().getTime() < startTime + milliSeconds) {
        continue;
      }
      return results;
    };
    body = '<html>' + '<head>' + '<meta http-equiv="Content-Type" content="text/html; ' + 'charset=UTF-8" />' + '</head>' + '<body>' + '<form action="/upload" method="post">' + '<textarea name="text" rows="20" cols="60"></textarea>' + '<input type="submit" value="Submit text" />' + '</form>' + '</body>' + '</html>';
    response.writeHead(200, {
      "Content-Type": "text/html"
    });
    response.write(body);
    return response.end();
  };

  upload = function(response, postData) {
    console.log("Request handler 'upload' was called.");
    debugger;
    response.writeHead(200, {
      "Content-Type": "text/plain"
    });
    response.write("You've sent: " + (querystring.parse(postData).text));
    return response.end();
  };

  exports.start = start;

  exports.upload = upload;

}).call(this);

//# sourceMappingURL=requestHandlers.js.map
